In [1]:
import pandas as pd
import numpy as np
data = {
'id_pracownika': [1,2,3,4,5,6,7,8,9,10,
11,12,13,14,15,16,17,18,19,20,
3,7,12,18,5, # duplikaty — te same id!
21,22,23,24,25],
'imie': ['Anna', 'Bartek', 'CELINA', 'darek', 'Ewa',
'Filip', 'Gosia', 'HENRYK', 'irena', 'Jan',
'Kasia', 'Leszek', 'Marta', 'norbert', 'OLGA',
'Piotr', 'Renata', 'sławek', 'Teresa', 'Urszula',
'CELINA', 'Gosia', 'Leszek', 'sławek', 'Ewa',
'Wanda', 'Xawery', 'Yvonne', 'Zbyszek', 'Agata'],
'dzial': ['Sprzedaz', 'IT', 'HR', 'sprzedaz', 'IT',
'HR', 'Sprzedaz', 'it', 'HR', 'Sprzedaz',
'IT', 'HR', 'sprzedaz', 'IT', 'HR',
'Sprzedaz', 'it', 'HR', 'Sprzedaz', 'IT',
'HR', 'Sprzedaz', 'HR', 'HR', 'IT',
'Sprzedaz', 'IT', 'hr', 'Sprzedaz', 'IT'],
'wynagrodzenie': ['4500', '6200', '3800', '5100', '7500',
'4200', '5800', '6900', '3500', '4800',
'7200', '4100', '5500', '6800', '3900',
'5200', '4700', '6100', '3800', '5400',
'3800', '5800', '4100', '6100', '7500',
'brak', '5000', None, '4300', '6600'],
'data_zatrudnienia': ['2020-03-15', '2019-07-22', '2021-01-10',
'2018-05-30', '2022-11-01', '2020-08-14',
'2019-12-05', '2021-06-18', '2017-09-23',
'2023-02-07', '2020-04-11', '2018-11-28',
'2022-07-15', '2019-03-19', '2021-10-08',
'2020-06-25', '2018-08-31', '2022-02-14',
'2019-05-07', '2021-09-20', '2021-01-10',
'2019-12-05', '2018-11-28', '2022-02-14',
'2022-11-01', '2023-01-15', '2022-05-20',
None, '2020-10-11', '2019-08-03'],
'ocena_roczna': [4.5, 3.8, None, 4.2, 5.0,
3.5, 4.7, None, 4.1, 3.9,
5.0, 4.3, 3.6, None, 4.8,
3.7, 4.4, 4.9, None, 3.8,
None, 4.7, 4.3, 4.9, 5.0,
4.6, None, 4.9, 3.5, 4.1]
}
df = pd.DataFrame(data)
print(f"Wczytano dataset: {df.shape[0]} wierszy, {df.shape[1]} kolumn")
df.head(10)

Wczytano dataset: 30 wierszy, 6 kolumn

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
1,2,Bartek,IT,6200,2019-07-22,3.8
2,3,CELINA,HR,3800,2021-01-10,NaN
3,4,darek,sprzedaz,5100,2018-05-30,4.2
4,5,Ewa,IT,7500,2022-11-01,5.0
5,6,Filip,HR,4200,2020-08-14,3.5
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7
7,8,HENRYK,it,6900,2021-06-18,NaN
8,9,irena,HR,3500,2017-09-23,4.1
9,10,Jan,Sprzedaz,4800,2023-02-07,3.9

## Zad 1a

In [3]:
print(df.info()) 
print(df.isna().sum()) 
print(df[df.isna().any(axis=1)])

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_pracownika      30 non-null     int64
 1   imie               30 non-null     str
 2   dzial              30 non-null     str
 3   wynagrodzenie      29 non-null     str
 4   data_zatrudnienia  29 non-null     str
 5   ocena_roczna       24 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 1.5 KB
None
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        1
data_zatrudnienia    1
ocena_roczna         6
dtype: int64
    id_pracownika     imie     dzial wynagrodzenie data_zatrudnienia  \
2               3   CELINA        HR          3800        2021-01-10
7               8   HENRYK        it          6900        2021-06-18
13             14  norbert        IT          6800        2019-03-19
18             19   Teresa  Sprzedaz          3800        2019-05-07
20              3   CELINA        HR          3800        2021-01-10
26             22   Xawery        IT          5000        2022-05-20
27             23   Yvonne        hr           NaN               NaN

    ocena_roczna
2            NaN
7            NaN
13           NaN
18           NaN
20           NaN
26           NaN
27           4.9

## Zad 1b

In [6]:
print(df['wynagrodzenie'].unique())
df['wynagrodzenie'] = df['wynagrodzenie'].replace('brak', np.nan)
df['wynagrodzenie'] = pd.to_numeric(df['wynagrodzenie'], errors='coerce')
print(df['wynagrodzenie'].isna().sum())

[4500. 6200. 3800. 5100. 7500. 4200. 5800. 6900. 3500. 4800. 7200. 4100.
 5500. 6800. 3900. 5200. 4700. 6100. 5400. 5150. 5000. 4300. 6600.]
0

## Zad 1c

In [7]:
mediana = df['wynagrodzenie'].median()
print(f"Mediana: {mediana}")
df['wynagrodzenie'] = df['wynagrodzenie'].fillna(mediana)

srednia = round(df['ocena_roczna'].mean(), 2)
print(f"Srednia ocena: {srednia}")
df['ocena_roczna'] = df['ocena_roczna'].fillna(srednia)

print(df.isna().sum())

Mediana: 5150.0
Srednia ocena: 4.34
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

## Zad 1d

In [8]:
df_bez_brakow = df.dropna(subset=['data_zatrudnienia'])
print(len(df_bez_brakow))

29

In [9]:
df2 = pd.DataFrame(data) # ta sama definicja 'data' co wyżej
# Najpierw napraw wynagrodzenie (tak samo jak w Ćw. 1b)
df2['wynagrodzenie'] = df2['wynagrodzenie'].replace('brak', np.nan)
df2['wynagrodzenie'] = pd.to_numeric(df2['wynagrodzenie'], errors='coerce')

## Zad 2a

In [10]:
print(df2.duplicated().sum())
display(df2[df2.duplicated()])
print(df2.duplicated(subset=['id_pracownika']).sum())
print(df2['id_pracownika'].value_counts().sort_index())

5

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
20,3,CELINA,HR,3800.0,2021-01-10,NaN
21,7,Gosia,Sprzedaz,5800.0,2019-12-05,4.7
22,12,Leszek,HR,4100.0,2018-11-28,4.3
23,18,sławek,HR,6100.0,2022-02-14,4.9
24,5,Ewa,IT,7500.0,2022-11-01,5.0

5
id_pracownika
1     1
2     1
3     2
4     1
5     2
6     1
7     2
8     1
9     1
10    1
11    1
12    2
13    1
14    1
15    1
16    1
17    1
18    2
19    1
20    1
21    1
22    1
23    1
24    1
25    1
Name: count, dtype: int64

## Zad 2b

In [11]:
df2 = df2.drop_duplicates().reset_index(drop=True)
print(df2.shape)

(25, 6)

## Zad 2c

In [12]:
print(df2['data_zatrudnienia'].dtype)
df2['data_zatrudnienia'] = pd.to_datetime(df2['data_zatrudnienia'], errors='coerce')
print(df2['data_zatrudnienia'].dtype)

df2['rok_zatrudnienia'] = df2['data_zatrudnienia'].dt.year
print(df2['rok_zatrudnienia'].dropna().unique())

str
datetime64[us]
[2020. 2019. 2021. 2018. 2022. 2017. 2023.]

## Zad 2d

In [13]:
print((df2['rok_zatrudnienia'] >= 2021).sum())
print((df2['wynagrodzenie'] > 6000).sum())

df2['dzial'] = df2['dzial'].str.strip().str.title()
print((df2['dzial'] == 'It').sum())

10
7
9

## Zad 3

In [14]:
df_clean = pd.DataFrame(data)

df_clean['wynagrodzenie'] = pd.to_numeric(df_clean['wynagrodzenie'].replace('brak', np.nan), errors='coerce')
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].fillna(df_clean['wynagrodzenie'].median())
df_clean['ocena_roczna'] = df_clean['ocena_roczna'].fillna(round(df_clean['ocena_roczna'].mean(), 2))

df_clean['imie'] = df_clean['imie'].str.strip().str.title()
df_clean['dzial'] = df_clean['dzial'].str.strip().str.title()
df_clean['dzial'] = df_clean['dzial'].str.replace('Hr', 'HR', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('It', 'IT', regex=False)

df_clean['data_zatrudnienia'] = pd.to_datetime(df_clean['data_zatrudnienia'], errors='coerce')

print("=== WERYFIKACJA ===")
print(f"Shape: {df_clean.shape}")
print(f"\nDtypes: \n{df_clean.dtypes}")
print(f"\nNaN per kolumna:\n{df_clean.isna().sum()}")
print(f"\nUnikalne działy: {sorted(df_clean['dzial'].unique())}")
print(f"\nPierwsze imiona: {df_clean['imie'].tolist()[:8]}")

print("\n=== PYTANIA BIZNESOWE ===")
print(df_clean.groupby('dzial')['wynagrodzenie'].mean().round(2))
print(df_clean.groupby('dzial')['ocena_roczna'].mean().round(2))
display(df_clean.nlargest(3, 'wynagrodzenie')[['imie', 'dzial', 'wynagrodzenie']])
print(df_clean['dzial'].value_counts())

=== WERYFIKACJA ===
Shape: (25, 6)

Dtypes:
id_pracownika                 int64
imie                            str
dzial                           str
wynagrodzenie               float64
data_zatrudnienia    datetime64[us]
ocena_roczna                float64
dtype: object

NaN per kolumna:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

Unikalne działy: ['HR', 'IT', 'Sprzedaz']

Pierwsze imiona: ['Anna', 'Bartek', 'Celina', 'Darek', 'Ewa', 'Filip', 'Gosia', 'Henryk']

=== PYTANIA BIZNESOWE ===
dzial
HR          4385.71
IT          6255.56
Sprzedaz    4900.00
Name: wynagrodzenie, dtype: float64
dzial
HR          4.39
IT          4.32
Sprzedaz    4.11
Name: ocena_roczna, dtype: float64

      imie dzial  wynagrodzenie
4      Ewa    IT         7500.0
10   Kasia    IT         7200.0
7   Henryk    IT         6900.0

dzial
Sprzedaz    9
IT          9
HR          7
Name: count, dtype: int64

## Ćw 3

In [15]:
df_clean = pd.DataFrame(data)

df_clean['wynagrodzenie'] = pd.to_numeric(df_clean['wynagrodzenie'].replace('brak', np.nan), errors='coerce')
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].fillna(df_clean['wynagrodzenie'].median())
df_clean['ocena_roczna'] = df_clean['ocena_roczna'].fillna(round(df_clean['ocena_roczna'].mean(), 2))

df_clean['imie'] = df_clean['imie'].str.strip().str.title()
df_clean['dzial'] = df_clean['dzial'].str.strip().str.title()
df_clean['dzial'] = df_clean['dzial'].str.replace('Hr', 'HR', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('It', 'IT', regex=False)

df_clean['data_zatrudnienia'] = pd.to_datetime(df_clean['data_zatrudnienia'], errors='coerce')

print("=== WERYFIKACJA ===")
print(f"Shape: {df_clean.shape}")
print(f"\nDtypes: \n{df_clean.dtypes}")
print(f"\nNaN per kolumna:\n{df_clean.isna().sum()}")
print(f"\nUnikalne działy: {sorted(df_clean['dzial'].unique())}")
print(f"\nPierwsze imiona: {df_clean['imie'].tolist()[:8]}")

print("\n=== PYTANIA BIZNESOWE ===")
print(df_clean.groupby('dzial')['wynagrodzenie'].mean().round(2))
print(df_clean.groupby('dzial')['ocena_roczna'].mean().round(2))
display(df_clean.nlargest(3, 'wynagrodzenie')[['imie', 'dzial', 'wynagrodzenie']])
print(df_clean['dzial'].value_counts())

=== WERYFIKACJA ===
Shape: (25, 6)

Dtypes:
id_pracownika                 int64
imie                            str
dzial                           str
wynagrodzenie               float64
data_zatrudnienia    datetime64[us]
ocena_roczna                float64
dtype: object

NaN per kolumna:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

Unikalne działy: ['HR', 'IT', 'Sprzedaz']

Pierwsze imiona: ['Anna', 'Bartek', 'Celina', 'Darek', 'Ewa', 'Filip', 'Gosia', 'Henryk']

=== PYTANIA BIZNESOWE ===
dzial
HR          4385.71
IT          6255.56
Sprzedaz    4900.00
Name: wynagrodzenie, dtype: float64
dzial
HR          4.39
IT          4.32
Sprzedaz    4.11
Name: ocena_roczna, dtype: float64

      imie dzial  wynagrodzenie
4      Ewa    IT         7500.0
10   Kasia    IT         7200.0
7   Henryk    IT         6900.0

dzial
Sprzedaz    9
IT          9
HR          7
Name: count, dtype: int64

In [16]:
df_str = pd.DataFrame(data)

## Zad 4a

In [17]:
print(df_str['imie'].str.isupper().sum())
print(df_str['imie'].str[0].str.islower().sum())
print(df_str['dzial'].str.lower().str.contains('sprzedaz').sum())

4
5
10

## Zad 4b

In [18]:
print(df_str['imie'].str.isupper().sum())
print(df_str['imie'].str[0].str.islower().sum())
print(df_str['dzial'].str.lower().str.contains('sprzedaz').sum())

4
5
10

## Zad 4c

In [19]:
display(df_str[df_str['dzial'].str.contains('IT|HR')])
display(df_str[df_str['imie'].str.contains('a', case=False)])
print(df_str['imie'].str.endswith('a').sum())

    id_pracownika     imie dzial wynagrodzenie data_zatrudnienia  ocena_roczna
1               2   Bartek    IT          6200        2019-07-22           3.8
2               3   CELINA    HR          3800        2021-01-10           NaN
4               5      Ewa    IT          7500        2022-11-01           5.0
5               6    Filip    HR          4200        2020-08-14           3.5
8               9    irena    HR          3500        2017-09-23           4.1
10             11    Kasia    IT          7200        2020-04-11           5.0
11             12   Leszek    HR          4100        2018-11-28           4.3
13             14  norbert    IT          6800        2019-03-19           NaN
14             15     OLGA    HR          3900        2021-10-08           4.8
17             18   sławek    HR          6100        2022-02-14           4.9
19             20  Urszula    IT          5400        2021-09-20           3.8
20              3   CELINA    HR          3800        2021-01-10           NaN
22             12   Leszek    HR          4100        2018-11-28           4.3
23             18   sławek    HR          6100        2022-02-14           4.9
24              5      Ewa    IT          7500        2022-11-01           5.0
26             22   Xawery    IT          5000        2022-05-20           NaN
29             25    Agata    IT          6600        2019-08-03           4.1

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
1,2,Bartek,IT,6200,2019-07-22,3.8
2,3,CELINA,HR,3800,2021-01-10,NaN
3,4,darek,sprzedaz,5100,2018-05-30,4.2
4,5,Ewa,IT,7500,2022-11-01,5.0
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7
8,9,irena,HR,3500,2017-09-23,4.1
9,10,Jan,Sprzedaz,4800,2023-02-07,3.9
10,11,Kasia,IT,7200,2020-04-11,5.0
12,13,Marta,sprzedaz,5500,2022-07-15,3.6
14,15,OLGA,HR,3900,2021-10-08,4.8
16,17,Renata,it,4700,2018-08-31,4.4
17,18,sławek,HR,6100,2022-02-14,4.9
18,19,Teresa,Sprzedaz,3800,2019-05-07,NaN
19,20,Urszula,IT,5400,2021-09-20,3.8
20,3,CELINA,HR,3800,2021-01-10,NaN
21,7,Gosia,Sprzedaz,5800,2019-12-05,4.7
23,18,sławek,HR,6100,2022-02-14,4.9
24,5,Ewa,IT,7500,2022-11-01,5.0
25,21,Wanda,Sprzedaz,brak,2023-01-15,4.6
26,22,Xawery,IT,5000,2022-05-20,NaN
29,25,Agata,IT,6600,2019-08-03,4.1

13